### ISSUE TITLE
Update `write_dwc()` to Camtrap DP 1.0

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camtrapdp#2]
Also describe mapping and provide and example, cf. https://inbo.github.io/movepub/reference/write_dwc.html#data

- [x] Update `dwc_audubon.csv` to `dwc_audiovisual.csv`. Also update in eml.xml, functions, tests and documentation.
- [x] identificationRemarks: remove mapping for featureType `none` and `other`
- [x] license is currently only set based on `path`, but would be better derived from `name` (see https://github.com/tdwg/camtrap-dp/issues/344)
- [x] type: add `MovingImage` (see inbo/camtrapdp#7)
- [x] rightsHolder: `rightsHolder` from contributors (select first)
- [x] collectionCode: from sources (select first)
- [x] eventID: `eventID`
- [x] eventDate: date range (see inbo/camtrapdp#13)
- [x] serviceExpectation: enable (see inbo/camtrapdp#10)
- [x] sex: map values
- [x] lifeStage: map values
- [x] eventRemarks: use boolean bait use
- [ ] ~eventRemarks: add deploymentGroups?~ wontfix

**Comment by sangovae** [comment]
In am confused about https://github.com/inbo/camtraptor/blob/45b72a292ac040d94af86c7131e992df41d3999a/R/write_dwc.R#L208

This code filters on rows that has mediaID NA's. Shouldn't it be opposite, that it omits NA's?
This code also joins by sequenceID, but that column is not present anymore in the new version. I guess it should now join by mediaID?

**Comment by sangovae** [comment]
> In am confused about https://github.com/inbo/camtraptor/blob/45b72a292ac040d94af86c7131e992df41d3999a/R/write_dwc.R#L208
> 
> This code filters on rows that has mediaID NA's. Shouldn't it be opposite, that it omits NA's? This code also joins by sequenceID, but that column is not present anymore in the new version. I guess it should now join by mediaID?

I figured it out, those lines link via sequenceID and the next lines via mediaID :-)

**Comment by peterdesmet** [comment]
Fixed in #55
